const homeScreenData = {
  header: 'For when you need to run the numbers',
  paragraph1: `
    This collection of situation-specific calculator applications now exists for 
    you and your monetary needs. 
    Use them to expand your prosperity and be accurate in your transactions.
    `,
  button1: 'Click for good fortune',
  lorem: `
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin porttitor diam ex, et maximus sem sollicitudin pellentesque. Aliquam erat volutpat. Nulla purus elit, ultricies vel ultricies gravida, feugiat non purus. Donec ut felis ac enim suscipit semper nec sed justo. In hac habitasse platea dictumst. Sed at pulvinar libero. Fusce mollis ligula in euismod auctor. Nam molestie ante quis turpis venenatis euismod. Cras sit amet elementum ex. Nulla facilisi.

  Sed vulputate tortor dui, nec lobortis erat varius eu. Suspendisse blandit sit amet massa in fringilla. Vestibulum massa lorem, sollicitudin sit amet efficitur sed, viverra nec urna. Morbi et blandit erat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce euismod tempus lacus, ut fermentum lectus eleifend eget. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec tincidunt massa ut mollis dictum. Proin in metus lacinia, laoreet libero eu, mattis diam. In consectetur tortor et neque molestie rutrum. Suspendisse non condimentum lorem, vel maximus ipsum. Morbi eget nisi at diam rhoncus feugiat sed sed lacus. Maecenas sodales ullamcorper nulla quis tempor. Suspendisse felis eros, auctor at pharetra vitae, maximus eget risus. Suspendisse potenti.
  
  Aliquam tristique aliquet rutrum. Nunc sit amet mi ut lacus viverra pretium. Vestibulum fringilla, dui at vulputate cursus, mi neque ultricies neque, quis fermentum justo nunc a enim. Vestibulum ornare nisl elit, non mattis eros egestas sed. Pellentesque pulvinar faucibus velit in pulvinar. Nulla facilisis dictum cursus. Mauris vel felis nec lectus congue eleifend. Aliquam non velit nisl. Nullam accumsan dolor non enim semper, sit amet ultrices odio aliquam. Pellentesque rhoncus auctor dolor, sed sodales leo dignissim sed. Ut id ante sed purus tincidunt ornare vitae quis elit. Sed vitae tempor nisi, et maximus lectus. In ac enim porttitor orci suscipit hendrerit in non nunc.
  
  Quisque pellentesque augue eget libero consequat scelerisque. Fusce enim lorem, eleifend eu convallis vel, varius bibendum sem. Aliquam non pellentesque nunc. Nunc non blandit mauris. Morbi facilisis nulla quis purus semper, sed vehicula augue elementum. Duis ultricies eu diam non pulvinar. Vivamus mi ligula, tempus sit amet iaculis eget, sodales a turpis. Pellentesque nec erat facilisis, placerat magna at, scelerisque felis. Quisque ac ipsum nec metus euismod placerat at vitae lacus. Fusce congue diam vitae purus tincidunt, eu facilisis nibh rhoncus. Sed gravida semper nunc ut aliquam. Suspendisse potenti. Sed lacinia auctor nunc, eget ultrices massa semper quis. Phasellus at fringilla enim, in volutpat purus. Aliquam in pharetra diam.
  
  Sed ac faucibus sapien. Sed consequat, mi eget sollicitudin condimentum, mauris orci vestibulum felis, quis tempor ipsum mi bibendum eros. Etiam auctor ultricies tortor tempus tincidunt. Morbi tristique ante dolor. Integer magna ipsum, efficitur blandit finibus at, tempor eu augue. Sed iaculis, metus vitae dictum rhoncus, ligula odio congue leo, ut vehicula mauris erat vel massa. Donec odio mauris, porttitor vitae pulvinar vel, mollis eu mi.
  
  Aenean at ultricies augue, et gravida massa. In quis metus eget ex pulvinar tempor. Integer dignissim nec metus sit amet pharetra. Integer finibus nisi eu mauris pellentesque luctus. Sed et arcu quis quam mollis elementum nec eget lacus. Maecenas at dui vestibulum, tincidunt elit ac, finibus nunc. Suspendisse euismod nec erat in luctus. Mauris vulputate ligula eget ullamcorper tempor. Sed pretium magna quis feugiat fermentum.
  
  Cras congue, arcu non venenatis luctus, tortor justo cursus justo, at efficitur mi nunc ac justo. Aliquam erat volutpat. Quisque molestie elit id commodo convallis. Pellentesque ante lectus, ullamcorper quis nisi et, mattis iaculis neque. Morbi ornare sit amet nunc sed aliquam. Nulla auctor sollicitudin ultrices. Curabitur faucibus at erat quis ullamcorper. Etiam nibh augue, bibendum quis lorem ac, aliquet accumsan diam. Pellentesque condimentum non justo sit amet egestas. Curabitur at sodales elit. Aenean vel imperdiet enim. Phasellus lobortis, leo et rhoncus convallis, massa ante vestibulum purus, eget placerat purus sapien id augue.
  
  Duis eu aliquam nulla, non auctor mauris. Mauris lorem mi, auctor a elementum non, pharetra sit amet enim. Aliquam feugiat aliquet augue id dapibus. Nam mattis elementum dolor id sollicitudin. Phasellus laoreet dictum sagittis. Aliquam erat volutpat. Vivamus hendrerit quis ipsum et faucibus. Cras egestas ante magna. Duis ligula urna, tincidunt in ex in, hendrerit ultrices felis. Duis aliquet semper feugiat. Nunc euismod sed turpis at vestibulum. Ut vitae metus lectus. Duis tincidunt, turpis eget laoreet eleifend, eros sem hendrerit ex, quis tempor tortor est eget nibh. Nullam eu mauris vel lacus euismod tempus. Vivamus quis nulla non lectus lobortis gravida ac vitae tortor. Morbi fermentum vehicula mi.
  
  Etiam viverra nisl sed velit viverra commodo. Maecenas ac massa ut orci sollicitudin facilisis. Integer volutpat accumsan augue, ac convallis mauris hendrerit tincidunt. Donec vel velit et tellus pellentesque eleifend. Sed volutpat metus purus, id tempor lorem consequat eleifend. Nulla dapibus elit ac maximus fringilla. Morbi fermentum ipsum mauris, ut luctus ex posuere id. Fusce feugiat condimentum dolor ac efficitur. Aenean nulla purus, fringilla at enim quis, laoreet viverra sapien. Sed ligula ante, euismod vitae mi a, viverra auctor risus. Duis nibh quam, scelerisque eu erat et, auctor semper metus. Phasellus rhoncus lorem ac magna porta, at auctor arcu rutrum. Pellentesque interdum, justo a sollicitudin molestie, tortor turpis dictum diam, non efficitur justo sapien in nulla.
  
  Donec sed ipsum arcu. Aenean in tempus est. Maecenas posuere, eros id congue hendrerit, odio tellus faucibus ex, ut vulputate nulla purus sit amet libero. Pellentesque venenatis eu ligula ultrices pellentesque. Nam tincidunt, lorem sed viverra porta, mauris metus eleifend quam, ac elementum dolor mauris nec augue. Suspendisse dapibus urna hendrerit dolor lobortis, pulvinar porttitor tortor porta. Aliquam facilisis vitae elit in dapibus.
  
  Nunc dignissim elementum lectus non tristique. Quisque aliquam, enim nec finibus euismod, urna libero faucibus tortor, id cursus velit mi in ipsum. Mauris tortor lectus, hendrerit in neque non, accumsan ultrices orci. Ut placerat enim eget arcu pretium, non pharetra nunc tristique. Curabitur fermentum massa ac nunc facilisis aliquet. Proin viverra gravida felis. Vivamus rutrum enim eros, eu finibus enim lacinia in. Sed egestas felis et auctor fermentum. Sed congue, urna in condimentum consequat, nibh tellus efficitur ipsum, in dapibus enim metus et lorem. Ut congue tincidunt erat, et dapibus dolor tristique vel. Vivamus urna nulla, auctor quis interdum eget, pharetra at odio. Proin blandit interdum fringilla.
  
  Aenean nisl est, suscipit ac metus nec, dignissim lacinia purus. Donec magna libero, luctus ut dapibus malesuada, dapibus nec massa. Maecenas finibus dolor eget porta vehicula. Suspendisse a ante at odio auctor sagittis. Vivamus tincidunt magna a lacus sagittis tempus. Aliquam egestas sapien sit amet leo ultrices, condimentum rhoncus lectus posuere. Pellentesque pretium nec sem hendrerit pretium. Cras dolor nulla, tempor ac eros in, aliquet feugiat neque. Nunc non quam et augue fermentum faucibus. Fusce sed eros at erat elementum pharetra et non orci. Phasellus facilisis nibh sit amet lectus dignissim volutpat.
  
  Morbi sit amet tortor ornare, pretium nulla nec, porta dolor. Praesent purus ipsum, ornare bibendum massa condimentum, suscipit facilisis metus. Donec laoreet erat in ipsum rutrum rutrum. Integer bibendum nisi purus, sed ullamcorper lorem dapibus at. Nullam ac enim vel leo pretium commodo at nec neque. Maecenas pharetra dolor at orci aliquam dignissim. Sed euismod odio ut felis rutrum congue. Vestibulum sed nibh lacus. Sed nec viverra libero. Aenean auctor nec dolor in cursus.
  
  Cras maximus urna quis imperdiet euismod. Pellentesque sit amet turpis diam. Phasellus ornare maximus est non rutrum. Curabitur vel diam turpis. Morbi sit amet imperdiet tellus. Donec luctus, mauris non condimentum vulputate, lorem mi egestas augue, in vestibulum dui augue at metus. Maecenas malesuada laoreet diam, vitae dignissim neque interdum in. Donec tempor justo a nisl fringilla interdum. Pellentesque sit amet viverra est. Aliquam vel malesuada lacus. Donec metus elit, efficitur at velit ut, fringilla eleifend risus. Mauris facilisis libero ac fringilla venenatis. Proin volutpat velit a neque ultricies elementum.
  
  Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut vitae auctor mi. Sed nunc mauris, tristique quis risus ut, congue euismod ex. Nullam non scelerisque lorem. Donec quis lacus at est mattis rhoncus. Praesent posuere dapibus nisi, eu suscipit enim aliquam sit amet. Nulla feugiat felis eu scelerisque fermentum. Morbi consectetur, libero et congue ultrices, orci lorem rhoncus nisl, eu mollis sem velit sed enim. Suspendisse vel molestie lorem. Proin urna magna, vulputate ac porttitor eget, lacinia id purus. Praesent lacinia consectetur iaculis. Phasellus fermentum massa nec dignissim mattis. Nullam dui mauris, elementum at ipsum quis, ultricies porttitor massa. Vestibulum molestie metus sed venenatis finibus.
  
  Ut lobortis mauris mauris, et iaculis lorem semper cursus. Pellentesque feugiat molestie nisi sit amet vestibulum. Proin pretium auctor tellus, at consectetur nulla posuere vitae. Duis in efficitur nibh. Donec faucibus, ante ultrices semper pretium, orci enim euismod odio, non blandit nulla nisl aliquam ante. Etiam sed justo placerat, maximus neque ullamcorper, tempus dolor. Fusce eu fringilla nisi. Vestibulum pellentesque sapien non leo rhoncus rutrum. Sed id arcu nisi. In vitae nunc sed lorem mattis imperdiet. Duis vitae ligula justo. Etiam sodales justo vitae lacus pharetra ornare. Integer aliquet risus vel dapibus sodales. Aliquam et pretium augue, a sollicitudin enim.
  
  Fusce vestibulum tincidunt consequat. Vivamus arcu nulla, efficitur id eros vitae, suscipit venenatis lectus. Vivamus a euismod mi. Etiam eleifend velit in enim hendrerit malesuada. Praesent et orci felis. Aenean eu ultrices ipsum. Donec tristique ullamcorper consequat. Sed ut nibh mattis, congue elit quis, feugiat mauris. Nullam consectetur, libero a vestibulum tempor, sapien urna egestas sapien, ullamcorper interdum felis purus ut orci. Nunc at nunc blandit, convallis lorem eu, pulvinar lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris ac laoreet felis. Cras gravida nisi sed felis elementum ultricies sed et odio. Integer finibus leo et elit pulvinar pellentesque vitae at libero. Etiam vel erat ut erat suscipit eleifend. Duis volutpat et mauris sit amet cursus.
  
  Phasellus porta massa quis interdum efficitur. Donec faucibus ex enim, quis aliquam elit suscipit euismod. Etiam leo libero, auctor aliquet vehicula ac, tincidunt a leo. Donec sit amet commodo felis. Phasellus posuere felis sit amet gravida facilisis. Integer tincidunt eget felis vel sodales. Fusce consectetur commodo porta. Suspendisse convallis massa orci, sit amet pulvinar lorem vestibulum vestibulum. Sed consectetur, purus a sagittis volutpat, urna libero sagittis justo, sit amet laoreet eros felis non purus. Duis at ligula magna. Suspendisse sapien sapien, tristique quis dui sed, hendrerit vulputate sapien. Aliquam a vehicula ipsum. Praesent laoreet, dolor eget imperdiet pellentesque, justo diam commodo mauris, sollicitudin cursus diam dui sed turpis. Cras aliquet magna vitae aliquam mattis. Sed laoreet nibh sed justo consequat ultricies.
  
  Sed vitae sem imperdiet, pretium risus quis, mattis metus. Praesent vel dignissim dolor. Curabitur porta lectus nec dui tincidunt congue. Quisque nec rhoncus arcu, at egestas tortor. Morbi quam est, sagittis at auctor vitae, placerat quis nisi. Nunc iaculis, magna eu condimentum dignissim, leo odio accumsan leo, ac accumsan urna magna id augue. Proin felis turpis, ultricies in dictum eget, fermentum ultricies ex. In tempus volutpat tortor, vehicula scelerisque arcu commodo sed. Nam et bibendum neque, quis interdum nisl. Sed tempus libero ut mauris vehicula, vel pellentesque elit varius.
  
  Sed nec faucibus mauris. Praesent augue odio, sollicitudin vitae placerat ut, elementum et ligula. Aenean augue arcu, suscipit vitae ligula ut, mollis sodales ligula. Nulla tempor dolor odio, eget consectetur tellus rhoncus id. Aenean ac pellentesque arcu. Donec eget pulvinar orci. Suspendisse potenti.
  
  In euismod, erat a venenatis interdum, eros arcu dictum erat, at efficitur ligula eros sit amet lectus. Nullam iaculis sem id porttitor euismod. Fusce cursus quam in sagittis maximus. Praesent varius sagittis luctus. In tristique purus lectus, sit amet tincidunt metus aliquet sit amet. Nulla auctor quam id est condimentum iaculis. Mauris vulputate elit sem, at iaculis magna dictum non. Phasellus mattis lorem vitae risus lacinia ultrices. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam sed diam pellentesque, imperdiet ante ut, vulputate ipsum.
  
  Nunc vestibulum gravida dolor, in facilisis mi viverra nec. Donec varius ex a nisi ullamcorper tincidunt. Morbi non nulla tempus, pellentesque velit sit amet, venenatis magna. Proin euismod blandit eros a auctor. Aliquam vitae massa id mauris semper aliquet non et ipsum. Maecenas tempus commodo faucibus. Donec orci nisl, efficitur a metus vitae, porttitor tristique lorem. Pellentesque in purus nec ipsum viverra vestibulum ut ut velit.
  
  Vivamus varius sapien quam, sit amet elementum dolor posuere sodales. Suspendisse sagittis velit sed ullamcorper vehicula. Proin eget ante vel dui ullamcorper placerat eget ut purus. Mauris dictum pulvinar orci, pulvinar vestibulum magna vestibulum lobortis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam urna dui, mattis ac feugiat eu, dapibus a turpis. Suspendisse porta hendrerit leo, vel lacinia mauris. Aliquam suscipit lorem at odio placerat, in vehicula elit dapibus. Pellentesque scelerisque, augue eu porttitor tristique, lacus leo laoreet ante, vel viverra sem orci non urna. Praesent dignissim, nisl ac pulvinar ornare, diam ante egestas nisl, at pulvinar ante nisi vitae tortor. Fusce in metus hendrerit, vehicula lacus id, malesuada tellus. Nunc vel aliquam lectus. Integer pellentesque lectus nulla, ut interdum lectus auctor non.
  
  Fusce non massa lorem. Duis tristique luctus leo nec semper. Sed vitae nunc iaculis leo suscipit suscipit id sit amet odio. Nam neque ex, commodo vitae magna bibendum, convallis viverra nisl. Sed interdum nibh ac aliquet feugiat. Aliquam pharetra non magna maximus sodales. Etiam auctor porta augue, vitae imperdiet sapien dictum et. Suspendisse efficitur at lacus tincidunt ullamcorper.
  
  Curabitur et ligula sed tortor interdum commodo in eu augue. Praesent congue tristique purus. Praesent sollicitudin enim quis eleifend pellentesque. Aliquam dapibus efficitur urna, ac euismod mauris placerat vel. Sed sit amet iaculis libero. Duis facilisis eleifend tempor. Fusce lobortis, turpis in imperdiet pellentesque, quam nisl ultrices lacus, nec consectetur nisl nibh et dolor.
  
  Mauris non sapien placerat, aliquam libero a, gravida elit. Aliquam porta sem tellus, eu ornare odio accumsan et. Integer aliquam turpis augue, nec mattis erat laoreet nec. Morbi lobortis malesuada odio at fringilla. Mauris sit amet facilisis ante. Mauris eu varius est. Donec consectetur rhoncus congue. Ut malesuada ac nulla sit amet commodo. Suspendisse nec sapien volutpat, tincidunt odio a, lobortis lectus. Aliquam non iaculis est. Nullam ut diam non mi sagittis sollicitudin. Nam pulvinar nec libero sit amet ultrices. Sed interdum nunc et libero vehicula, eu pretium turpis tristique.
  
  Nam tincidunt augue a hendrerit tincidunt. Suspendisse pellentesque lorem non nisi blandit, id pharetra sem vehicula. Aenean finibus finibus ante ac volutpat. Integer ac erat suscipit, pellentesque odio ac, tempor ligula. Aenean a mollis tellus. Vestibulum lobortis eu ex nec iaculis. Aenean faucibus pellentesque velit hendrerit aliquam. Morbi egestas laoreet dapibus. Nam posuere condimentum dui vel rhoncus. Donec massa magna, posuere vitae rutrum a, laoreet sed nibh.
  
  Mauris euismod erat arcu, id auctor nunc mollis sit amet. Duis sed lorem ut purus bibendum volutpat. Sed ultricies vel quam id cursus. Duis sit amet lacinia magna, et aliquam purus. Aliquam erat volutpat. Vestibulum condimentum tortor sed efficitur rutrum. Aliquam eleifend eget velit sit amet tempor. Fusce vel enim leo. Suspendisse potenti. Sed lobortis ultrices nunc vitae efficitur. Fusce ultrices justo vel fringilla rhoncus. Duis ac nulla nulla. Quisque eu massa maximus, volutpat ipsum vel, luctus velit.
  
  Maecenas tristique justo non purus laoreet facilisis. Quisque rutrum dignissim turpis. Curabitur in dapibus eros. Suspendisse sit amet libero scelerisque, convallis sapien vitae, elementum urna. Aenean id condimentum felis. Etiam velit nibh, lobortis non leo in, porta facilisis magna. Curabitur vitae magna placerat, sodales velit sit amet, consequat elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In auctor viverra semper. Quisque faucibus orci est, sed eleifend massa posuere ac. Mauris vestibulum quam a nibh luctus, a vestibulum diam semper. Sed eleifend lorem felis, venenatis vehicula ipsum vulputate ac. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed nec tellus at orci dignissim tincidunt. Morbi rutrum diam id ipsum venenatis, a mattis mi euismod.
  
  Vivamus ultricies, mauris eu congue varius, magna lorem dignissim lectus, in ornare sapien ante sodales neque. In commodo, est ut aliquet pharetra, lacus lectus cursus ex, tempor sagittis tortor magna vel nisi. In leo ex, porttitor eget faucibus vel, iaculis vitae ex. Donec volutpat mauris ligula, et scelerisque mauris tincidunt non. Donec vitae tellus vel arcu faucibus euismod sit amet quis velit. Suspendisse potenti. Donec facilisis convallis ligula, in scelerisque odio auctor sed. In sagittis dictum sem at iaculis. Etiam efficitur erat nec viverra eleifend.
  
  Quisque vestibulum varius porttitor. Sed vulputate convallis odio, non accumsan neque interdum at. Morbi accumsan, dolor eget condimentum blandit, ex eros mattis magna, a condimentum massa enim sit amet lorem. Cras urna orci, blandit a molestie vehicula, tempus in ligula. Quisque vel massa ut lectus sollicitudin scelerisque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent ut ante dui. Aliquam placerat vel tortor quis bibendum. Etiam pretium nunc vitae imperdiet tristique. Sed bibendum odio in purus tempus finibus. Vivamus mattis consequat tempus. Aliquam bibendum libero nulla, non faucibus lacus lacinia at.
  
  Vestibulum suscipit tellus ac arcu ultrices venenatis. Aliquam finibus tellus tortor, mattis molestie dolor eleifend ut. Donec ullamcorper, augue quis placerat rhoncus, neque ipsum auctor risus, eu maximus neque sem ac ex. Sed laoreet iaculis tempus. Praesent congue, risus id sodales finibus, augue eros congue nisi, nec luctus ante eros sit amet ligula. Duis tincidunt tristique arcu vitae tincidunt. Mauris suscipit auctor sem nec convallis. Curabitur in aliquam libero. Duis quis tempor ex. Donec ornare sem eros, ut rhoncus dui consectetur ut. Aenean ut tempus nibh.
  
  Donec lobortis ultricies ligula, eu venenatis nisl scelerisque at. Etiam dapibus posuere dictum. Vestibulum porttitor lacus neque, sit amet posuere nisi tempus non. Phasellus sit amet convallis arcu. Etiam condimentum molestie nisl vel ultricies. Nullam quis leo ex. Nunc quis elementum eros, et suscipit magna. Nulla ante sapien, eleifend sed augue a, interdum elementum ante. In ac hendrerit purus. Fusce tincidunt nunc at velit sollicitudin volutpat ac ut odio. Vivamus imperdiet odio eu diam pharetra rhoncus. Vivamus tempor urna massa, nec pretium augue commodo sit amet. In vitae auctor nulla.
  
  Nunc maximus, velit eu pellentesque pharetra, justo dui rutrum ipsum, in fringilla nulla leo nec libero. Vivamus quis libero sed sem vestibulum tincidunt. Donec laoreet lacus et nisl maximus, bibendum tincidunt sem commodo. Donec sed diam a sem tristique feugiat nec ut mi. Aliquam sodales nisi sed enim interdum sollicitudin. Donec imperdiet enim eu interdum porttitor. Fusce at tempor turpis. Ut pulvinar tellus scelerisque turpis placerat molestie. Etiam felis velit, elementum ut consectetur ac, pellentesque accumsan neque. Mauris rhoncus maximus massa, sed vehicula orci dapibus sed. Nunc vestibulum congue volutpat. Duis rutrum at lacus in aliquam. Ut commodo fermentum gravida. Donec vehicula accumsan risus, sit amet egestas velit imperdiet in.
  
  Etiam quis bibendum diam. Quisque sit amet lobortis eros, et accumsan erat. Nulla facilisi. Fusce diam urna, rhoncus id ex non, dapibus mollis ipsum. Fusce sollicitudin odio a ante placerat faucibus. Quisque lacinia, risus eu ornare pretium, lectus tortor feugiat mauris, id feugiat ex mauris at mauris. Integer id interdum sapien. Sed massa urna, tincidunt et dui eu, tincidunt auctor lorem.
  
  Proin scelerisque vehicula mauris, eget porta nisl bibendum non. Nam convallis cursus sapien sed ornare. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris eget libero massa. Vivamus urna lectus, pretium sit amet dolor id, pretium dictum ligula. Nam faucibus, tellus vel ultricies vehicula, ex felis pulvinar nibh, ut porta sapien nisl at mi. Cras vel pretium augue.
  
  Vivamus non metus purus. Integer fringilla dignissim aliquet. Nam vulputate ut magna nec efficitur. Fusce ultricies dui id mauris condimentum, ac aliquet sapien auctor. Proin ac semper libero. Praesent velit ipsum, hendrerit non mauris ac, sagittis bibendum mi. Aliquam feugiat, sem in auctor cursus, tortor mi tempor diam, eget congue nisi tellus eu est. Mauris venenatis nisl sem, nec lobortis diam fringilla eget. Vestibulum sit amet ipsum vitae odio maximus maximus. Ut urna tortor, sodales ac diam non, sagittis blandit nulla. Morbi porttitor ut sem eu tincidunt.
  
  Etiam enim ipsum, lobortis vel felis sed, sagittis viverra lorem. Nunc mattis massa sed ornare porttitor. Praesent ullamcorper, mi ut maximus ullamcorper, lorem turpis sollicitudin est, id consequat felis ante eu augue. Nulla a hendrerit magna, id dictum nunc. Mauris ut aliquam ipsum. Aenean congue in nulla sit amet facilisis. Sed gravida nisi eget gravida dignissim. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce at leo commodo, finibus massa et, malesuada ipsum. Morbi non ex libero. Nam vel dictum dolor. Curabitur nulla quam, pharetra sit amet leo non, luctus condimentum ante. Quisque tristique facilisis mauris, non ullamcorper nisi fringilla non. Nunc nibh risus, vehicula porttitor sem in, malesuada venenatis felis. Nullam vitae metus ultricies, malesuada sapien vitae, porta sem. Nulla facilisi.
  
  Mauris tempus velit a felis sagittis condimentum. Aenean in odio quis turpis sodales ultrices. Donec rhoncus consequat sapien, a tristique mauris lobortis quis. Aenean feugiat et nisi ac pretium. Ut vestibulum bibendum purus, ac facilisis dolor. Pellentesque aliquet commodo augue ut gravida. Nullam consequat commodo malesuada. Nullam auctor convallis velit, in cursus urna posuere vitae. Suspendisse bibendum nec eros at fringilla. Suspendisse sed volutpat ex, sit amet gravida justo. Quisque aliquam vestibulum urna, at porttitor massa ullamcorper nec. Ut pharetra pulvinar sodales. Suspendisse at nulla orci. Vestibulum ut mauris mattis, consequat purus vitae, auctor dolor. Pellentesque congue hendrerit malesuada.
  
  Nam aliquet ut felis sit amet interdum. Etiam commodo sodales ultricies. Aliquam at mollis metus. Cras consectetur volutpat tellus vel euismod. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed massa diam, volutpat vitae ante vel, venenatis mollis velit. Aenean a ligula id enim facilisis varius. Etiam in sodales purus. Vivamus dictum vitae risus non gravida.
  
  Suspendisse potenti. Donec ac turpis et libero dignissim accumsan vel a mi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur lobortis nibh id eros iaculis euismod. Cras fermentum, lectus in imperdiet tincidunt, orci tortor pharetra orci, ut hendrerit est elit nec purus. Praesent vulputate sapien sed sem eleifend, non accumsan lacus vestibulum. Quisque eget orci sit amet odio ornare vehicula a eu orci.
  
  Ut eu venenatis orci. Mauris gravida efficitur sapien, ac bibendum enim. Aenean a tincidunt felis. Suspendisse volutpat neque leo, id viverra dui lacinia sed. Sed eget ullamcorper augue, malesuada fermentum orci. Nulla venenatis massa quis sem laoreet, a blandit metus interdum. Donec ut mauris ut diam fringilla lacinia. Aliquam a ligula eu velit accumsan hendrerit. Fusce eleifend nisi nec arcu efficitur semper. Quisque tincidunt elit vitae neque lacinia egestas tempus eu lectus. Pellentesque pretium sapien magna, sit amet molestie mauris aliquet quis. Nam interdum aliquet diam, lacinia tempor purus tincidunt eget. Vivamus placerat mollis mollis. Phasellus faucibus aliquet neque, vel tincidunt augue auctor id. Aliquam erat volutpat. Nulla et dignissim ipsum.
  
  Mauris a purus sagittis sapien aliquam porta. Nam fermentum porttitor lacus id vehicula. Donec quis lacinia dui. Praesent faucibus at magna id mollis. Donec a urna eros. Curabitur dignissim tristique risus quis scelerisque. Nulla tincidunt, enim ut dictum sodales, metus eros bibendum velit, eu pulvinar lacus ligula vel nulla. Integer lectus erat, malesuada a porta sit amet, dictum eu odio. Donec iaculis ligula sed dui suscipit rutrum.
  
  Praesent suscipit ultricies mauris, at tristique nisl dictum quis. Cras quis tristique purus. Nulla eget ante et velit dignissim eleifend. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu orci condimentum, lacinia nisl vehicula, molestie tortor. Nam tincidunt sed risus volutpat viverra. Proin sodales est a ipsum varius porttitor.
  
  Vestibulum pretium lorem eu odio suscipit, eu rutrum quam placerat. Aenean molestie tellus et nunc tincidunt, ac ultrices massa rhoncus. Quisque ut diam vel mauris molestie sodales vitae sit amet ante. Donec scelerisque pellentesque vulputate. Suspendisse sodales sollicitudin turpis eget molestie. In quam diam, sodales id lectus vitae, consequat ullamcorper nulla. Morbi dictum at tellus at ultrices. Pellentesque non ipsum nunc. Maecenas scelerisque maximus urna, commodo viverra nisi malesuada vitae. Nullam facilisis mauris vitae iaculis porttitor. Integer eget varius dui, id viverra leo. Vivamus erat tortor, aliquet a metus in, dignissim rhoncus dolor. Maecenas dictum neque nec elit porta, sit amet facilisis nunc fringilla. Aliquam semper accumsan mauris, in sollicitudin lectus sollicitudin vel. Phasellus sit amet pellentesque turpis. Fusce accumsan posuere massa, sit amet imperdiet velit sagittis nec.
  
  Nullam pretium eget sapien in venenatis. Quisque viverra diam mauris, id dignissim risus tincidunt vel. Integer lacinia lorem ac felis pretium dapibus. Sed laoreet, libero id pellentesque mattis, enim nisl mattis nisl, eget rhoncus neque velit eu sapien. Curabitur faucibus consectetur nisl, sed semper enim pharetra vulputate. Phasellus aliquet orci a eros pretium vulputate. Pellentesque placerat, mi nec elementum porta, nisl nulla consequat urna, sit amet semper lorem justo id tortor. Mauris justo arcu, iaculis eu ipsum vitae, molestie porta nunc. In efficitur ligula sit amet erat egestas ultricies. In sit amet mattis erat. Ut arcu sapien, aliquam id est et, eleifend ultricies lectus. Nulla at interdum lorem. Donec eget placerat metus. Donec cursus malesuada ultricies. Etiam metus leo, maximus vel augue sed, suscipit porta felis.
  
  Mauris lobortis rutrum sagittis. Donec volutpat ex in quam sagittis, eu porta turpis pulvinar. Vivamus condimentum dolor in tellus ultricies mattis. Vivamus accumsan finibus libero, id eleifend metus efficitur ac. Curabitur fermentum sit amet libero a tristique. Phasellus id ipsum id est egestas elementum. Fusce non nisi vel sapien dignissim tincidunt. In vitae justo elit. Proin ut ante varius, imperdiet ex non, interdum felis.
  
  Aliquam at urna nec tortor gravida pulvinar a eu erat. Pellentesque scelerisque ac nisl et faucibus. Nulla nec finibus libero, eget commodo mauris. Proin posuere sit amet elit eget ultricies. Nam a massa placerat, dignissim neque eget, laoreet lorem. Phasellus venenatis rhoncus mi sit amet molestie. Maecenas volutpat velit at lorem efficitur, eget rhoncus lacus ultrices. Maecenas ut enim sem. Cras a dapibus orci.
  
  Praesent non bibendum purus. Maecenas ut posuere turpis. Quisque rutrum orci ac pretium fermentum. Vivamus vehicula semper lacus quis facilisis. Ut blandit ultricies ex, eget volutpat purus condimentum eget. Donec tristique facilisis lacus nec lobortis. Sed at nunc id orci ornare blandit a nec orci. Phasellus eget pretium enim, sed ultrices dolor. Cras tempor molestie ligula vitae pretium. Aliquam vitae tristique mi. Nullam venenatis, augue at bibendum semper, elit est cursus nisl, quis maximus velit augue sed leo. Duis eu turpis vestibulum, finibus nisl eu, porttitor velit.
  
  Donec elementum neque nulla, quis vehicula massa dignissim eget. Donec mi orci, ornare eget ex ut, sagittis tincidunt leo. Quisque faucibus, dui et vehicula cursus, elit velit condimentum sem, id aliquam quam dolor iaculis ante. Morbi finibus egestas leo. Maecenas accumsan interdum ligula eu feugiat. Vivamus rhoncus, urna ut egestas iaculis, ante turpis consequat sem, ut consequat augue orci in dui. Proin nisl diam, tempus sed laoreet non, lobortis sit amet erat. Nulla molestie justo ac gravida accumsan. Cras eu scelerisque quam.
  `,
};

export default homeScreenData;
